# Generated by Django 4.1 on 2023-04-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
